---
# markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Set sensible line length limits for better readability
MD013:
  line_length: 300
  heading_line_length: 150
  code_block_line_length: 350
  tables: false

# Allow duplicate headings in decision logs and structured documents
MD024:
  siblings_only: true

# Disallow raw HTML
MD033: true

# Disallow emphasis as headings
MD036: true

# Disable code block style check (conflicts with MkDocs admonitions)
MD046: false

# Disable single H1 check (MkDocs meta plugin title counts as first heading)
MD025: false

# Disable link fragment validation (conflicts with MkDocs pymdownx.slugs config)
# MkDocs uses separator: "_" and case: lower, which markdownlint can't detect
MD051: false
