# yaml-language-server: $schema=https://readability.adaptive-enforcement-lab.com/latest/schemas/config.json
# Content Analyzer Configuration
# Readability thresholds based on US grade levels:
#   8-10  = MIL-STD-38784 (military technical manuals)
#   12    = High school senior
#   14    = College sophomore
#   16    = College senior
#   18+   = Graduate level

thresholds:
  max_grade: 16    # College senior (default for most content)
  max_ari: 16
  max_fog: 18
  min_ease: 25
  max_lines: 375
  min_words: 200   # Skip readability checks for code-heavy docs

overrides:
  # About pages: Allow more complex prose for brand/mission content
  - path: docs/about/
    thresholds:
      max_grade: 18
      max_ari: 18
      min_ease: 20

  # Blog posts: MIL-STD-38784 level (accessible to broader audience)
  # Note: Blog posts don't need min_ease enforcement (narrative style varies)
  - path: docs/blog/
    thresholds:
      max_grade: 12
      max_ari: 12
      min_ease: 0

  # Patterns: Graduate level (technical deep-dives)
  # Reference-style docs with lists/tables break readability formulas
  # Admonitions optional - many pages are pure reference material
  - path: docs/patterns/
    thresholds:
      max_grade: 50
      max_ari: 60
      max_fog: 50
      min_ease: -100

  # Build: Graduate+ level (advanced technical content)
  # Reference-style docs with lists/tables break readability formulas
  # Admonitions optional - many pages are pure reference material
  - path: docs/build/
    thresholds:
      max_grade: 50
      max_ari: 60
      max_fog: 50
      min_ease: -100

  # Enforce: Graduate+ level (policy enforcement content)
  # Reference-style docs with lists/tables break readability formulas
  # Admonitions optional - many pages are pure reference material
  - path: docs/enforce/
    thresholds:
      max_grade: 50
      max_ari: 60
      max_fog: 50
      min_ease: -100

  # Secure: Graduate+ level (security tooling content)
  # Reference-style docs with lists/tables break readability formulas
  # Admonitions optional - many pages are pure reference material
  - path: docs/secure/
    thresholds:
      max_grade: 50
      max_ari: 60
      max_fog: 50
      min_ease: -100

  # Reference: Glossaries and reference material
  # Short definitions and technical terms break readability formulas
  # Intentionally concise, direct sentences for quick reference
  - path: docs/reference/
    thresholds:
      max_grade: 50
      max_ari: 60
      max_fog: 50
      min_ease: -100

  # Includes: Snippet files for site-wide features
  # Not meant to be read as standalone documents
  - path: docs/includes/
    exclude: true
