name: Export OpenTelemetry Traces to Dash0
on:
  workflow_run:
    workflows:
      - "Build Pipeline"
      - "Release Pipeline"
      - "Documentation Quality"
    types:
      - completed
jobs:
  export-trace:
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: corentinmusard/otel-cicd-action@895874bfae14f840e3032f1a14c3f2b45c93f4af # 4.1.1
        with:
          otlpEndpoint: ${{ secrets.DASH0_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.DASH0_OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
